databaseChangeLog:
  - changeSet:
      id: in-out-create-in-table-application
      author: G4IT Dev Team
      changes:
        - createTable:
            tableName: in_application
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  incrementBy: 100
                  constraints:
                    primaryKey: true
                    primaryKeyName: in_application_pk
              - column:
                  name: name
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: inventory_id
                  type: bigint
                  constraints:
                    nullable: true
                    foreignKeyName: in_application_inventory_id_fk
                    references: inventory(id)
                    deleteCascade: true
              - column:
                  name: digital_service_uid
                  type: varchar(255)
                  constraints:
                    nullable: true
                    foreignKeyName: in_application_digital_service_fk
                    references: digital_service(uid)
              - column:
                  name: physical_equipment_name
                  type: varchar(255)
              - column:
                  name: virtual_equipment_name
                  type: varchar(255)
              - column:
                  name: environment
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: common_filters
                  type: varchar(255) array
              - column:
                  name: filters
                  type: varchar(255) array
              - column:
                  name: creation_date
                  type: timestamp
              - column:
                  name: last_update_date
                  type: timestamp
              - addUniqueConstraint:
                  columnNames: name, digital_service_uid, inventory_id
                  constraintName: in_application_unique
                  tableName: in_application

  - changeSet:
      id: in-out-create-out-table-application
      author: G4IT Dev Team
      changes:
        - createTable:
            tableName: out_application
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
                  incrementBy: 100
                  constraints:
                    primaryKey: true
                    primaryKeyName: out_application_pk
              - column:
                  name: name
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: criterion
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: lifecycle_step
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: task_id
                  type: bigint
                  constraints:
                    nullable: false
                    foreignKeyName: application_task_id_fk
                    references: task(id)
                    deleteCascade: true
              - column:
                  name: environment
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: equipment_type
                  type: varchar(255)
              - column:
                  name: location
                  type: varchar(255)
              - column:
                  name: engine_name
                  type: varchar(255)
              - column:
                  name: engine_version
                  type: varchar(255)
              - column:
                  name: referential_version
                  type: varchar(255)
              - column:
                  name: status_indicator
                  type: varchar(255)
                  constraints:
                    nullable: false
              - column:
                  name: quantity
                  type: float
                  constraints:
                    nullable: false
              - column:
                  name: unit_impact
                  type: float
              - column:
                  name: people_eq_impact
                  type: float
              - column:
                  name: electricity_consumption
                  type: float
              - column:
                  name: unit
                  type: varchar(255)
              - column:
                  name: common_filters
                  type: varchar(255) array
              - column:
                  name: filters
                  type: varchar(255) array
              - column:
                  name: filters_physical_equipment
                  type: varchar(255) array
              - column:
                  name: filters_virtual_equipment
                  type: varchar(255) array
              - column:
                  name: errors
                  type: varchar(255) array

  - changeSet:
      id: in-out-add-index-application
      author: G4IT Dev Team
      changes:
        - createIndex:
            tableName: in_application
            indexName: idx_in_application_inventory_id_vi_eq_name_ph_eq_name
            columns:
              - column:
                  name: inventory_id
              - column:
                  name: physical_equipment_name
              - column:
                  name: virtual_equipment_name
        - createIndex:
            tableName: out_application
            indexName: idx_out_application_task_id
            columns:
              - column:
                  name: task_id
                  descending: true
